import { useContext } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { Store } from '../utils/Store'

export default function Layout({ title, children }) {
  const { state } = useContext(Store)
  const { cart } = state

  return (
    <>
      <Head>
        <title>{title ? title + ' ' + '-' + " " + 'Ecommerce' : 'Ecommerce - nextjs-mongodb-tailwind'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex min-h-screen flex-col justify-between'>
        <header>
          <nav className='flex h-12 px-4 items-center justify-between shadow-md'>
            <Link href='/'>
              <a className='text-lg font-bold'>ECommerce</a>
            </Link>
            <div>
              <Link href='/cart'><a className='p-2'>Cart
                {cart.cartItems.length > 0 && (
                  <span className='ml-1 py-1 px-2 text-xs font-bold rounded-full bg-primary text-white'>
                    {cart.cartItems.reduce((a, c) => a + c.quantity, 0)}
                  </span>
                )}
              </a></Link>
              <Link href='/login'><a className='p-2'>Login</a></Link>
            </div>
          </nav>
        </header>
        <main className='container m-auto mt-4'>{children}</main>
        <footer className='flex h-10 justify-center items-center shadow-inner text-sm'>Copyright &copy; 2022 ECommerce</footer>
      </div>
    </>
  )
}
