import { useContext, useEffect, useState } from 'react'
import { useSession } from 'next-auth/react'
import Head from 'next/head'
import Link from 'next/link'
import { Store } from '../utils/Store'
import 'react-toastify/dist/ReactToastify.css'
import { ToastContainer } from 'react-toastify'

export default function Layout({ title, children }) {

  const { data: session, status } = useSession()

  const { state } = useContext(Store)
  const { cart } = state
  const [cartItemsCount, setCartItemsCount] = useState(0)

  useEffect(() => {
    setCartItemsCount(cart.cartItems.reduce((a, c) => a + c.quantity, 0))
  }, [cart.cartItems])

  return (
    <>
      <Head>
        <title>{title ? title + ' ' + '-' + " " + 'Ecommerce' : 'Ecommerce - nextjs-mongodb-tailwind'}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer position="top-right" limit={1} />
      <div className='flex min-h-screen flex-col justify-between'>
        <header>
          <nav className='flex h-12 px-4 items-center justify-between shadow-md'>
            <Link href='/'>
              <a className='text-lg font-bold'>ECommerce</a>
            </Link>
            <div>
              <Link href='/cart'><a className='p-2'>
                Cart
                {cartItemsCount > 0 && (
                  <span className='ml-1 py-1 px-2 text-xs font-bold rounded-full bg-primary text-white'>
                    {cartItemsCount}
                  </span>
                )}
              </a></Link>
              {status === 'loading'
                ? 'Loading'
                : session?.user
                  ? session.user.name
                  :
                  <Link href='/login'>
                    <a className='p-2'>
                      Login
                    </a>
                  </Link>
              }
            </div>
          </nav>
        </header>
        <main className='container m-auto mt-4'>{children}</main>
        <footer className='flex h-10 justify-center items-center shadow-inner text-sm'>Copyright &copy; 2022 ECommerce</footer>
      </div>
    </>
  )
}
